version: '3.4'

networks:
  test_network:
    external: true

volumes:
  candidates_db_data: {}

services:
  api:
      build:
        context: .
        dockerfile: ./provision/api/Dockerfile
      container_name: ${APP}_api
      restart: unless-stopped
      tty: true
      env_file:
        - .env
      ports:
        - '8000:8000'
      depends_on:
        - db
      links:
        - db
      networks:
        - test_network

  db:
    image: bitnami/postgresql:15
    container_name: ${APP}_db
    env_file:
      - .env
    environment:
      - POSTGRESQL_TIMEZONE=${TIME_ZONE}
      - POSTGRESQL_LOG_TIMEZONE=${TIME_ZONE}
    ports:
      - "5432:5432"
    volumes:
      - candidates_db_data:/bitnami/postgresql
    networks:
      - test_network